In [2]:
import numpy as np
import matplotlib.pyplot as plt
# from utils import plot_lines

In [9]:
A = np.array([
        [-1,3],
        [3,2]
    ])

b = np.array([[7],[1]])

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)                

Matrix A:
[[-1  3]
 [ 3  2]]

Array b:
[[7]
 [1]]


In [10]:
A_system= np.hstack((A,b))
print(A_system)

[[-1  3  7]
 [ 3  2  1]]
