In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
c = np.arange(-10, 20, 2)
print(c)

[-10  -8  -6  -4  -2   0   2   4   6   8  10  12  14  16  18]


In [11]:
newLine= np.arange(1,40)
print(newLine)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [20]:
line_space= np.linspace(0,20,6, dtype=int)
line_space

array([ 0,  4,  8, 12, 16, 20])

In [26]:
string_array= np.array(["my name  is Ehsanullah"])
print(string_array)
print(string_array.dtype)

['my name  is Ehsanullah']
<U22


In [31]:
one_new= np.ones(10, dtype=int)
one_new

empty_one= np.empty(3)
empty_one

array([1., 1., 1.])

In [37]:
random_rand= np.random.rand(20)
print(random_rand)

[0.79747356 0.06355086 0.97195484 0.82498734 0.86325028 0.24354688
 0.65105913 0.51149096 0.15161558 0.31941181 0.10322875 0.81254544
 0.49165185 0.44110342 0.3922472  0.80975752 0.33650038 0.3628545
 0.22739254 0.74589483]


In [ ]:
matrix1= np.array([[3,3,4,5], 
                   [6,2,7,4]])
matrix2=np.array([[3,4,5,6],
                  [3,4,5,5]])


print(matrix1)
print(matrix2)


[[3 3 4 5]
 [6 2 7 4]]
[[3 4 5 6]
 [3 4 5 5]]


In [50]:
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

multi_dim_arr = np.reshape(one_dim_arr,(3,2))
print(multi_dim_arr)
print(multi_dim_arr.ndim)
print(multi_dim_arr.shape)
print(multi_dim_arr.size)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6


In [52]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])

vert_stack = np.vstack((a1, a2))
print(vert_stack)
hor_stack= np.hstack((a1,a2))
print(hor_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [ ]:
A = np.array([[4, 9, 9],
              [9, 1, 6],
              [9, 2, 3]])
print("Matrix A (3 by 3):\n", A)

B = np.array([[2, 2],
              [5, 7],
              [4, 4]])
print("Matrix B (3 by 2):\n", B)

Matrix A (3 by 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 by 2):
 [[2 2]
 [5 7]
 [4 4]]


In [4]:
w = np.zeros((3,1))
x= np.array([[3,4,5],
            [45,6,7],
            [56,8,7]])
print(x[0,1])
print(w[0,0])
 

4
0.0


In [ ]:
def transformation(v):
 A = np.array([[3,2],
              [-1,3]])
 return A @ v
  
v= np.array([[0],
            [1]]) 
w=transformation(v)

print(w)



[[ 0  0]
 [-1  3]]


In [10]:
A = [[3, 2],
     [-1, 3]]
B = [[5], [4]]

rows_A, cols_A = len(A), len(A[0])
rows_B, cols_B = len(B), len(B[0])

result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]
print(result)
  
print(rows_A)

[[0], [0]]
2


In [14]:
def multiplication(A,B):
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])
    
    
    result= [[0 for _ in range(cols_B)] for _ in range(rows_A)]
    
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j]= A[i][k] * B[k][j]
                
    return result


A = [[3, 2], 
     [-1, 3]]
v = [[5], 
     [4]]

print(multiplication(A, v)) 

            
        

    

[[8], [12]]
