In [1]:
import numpy as np

In [2]:
with open("data.txt", "r") as fi:
    data= fi.read()
    print(data)

0100100000100001011010010000000001111000000100010111100000010001111110011001000001010011100100001111100110100011001000010001001011111001100100001100000000000011011110000001000110001000000100010011101010010000


In [20]:
binary_rep= []
for i in range(0,len(data),16):
     binary_rep.append(data[i:i+16])
print(binary_rep)                    

['0100100000100001', '0110100100000000', '0111100000010001', '0111100000010001', '1111100110010000', '0101001110010000', '1111100110100011', '0010000100010010', '1111100110010000', '1100000000000011', '0111100000010001', '1000100000010001', '0011101010010000']


In [ ]:
def block_creator(str_rep):
    _list= list(map(lambda i:int(i), str_rep))
    block =np.array(_list)
    block= block.reshape((4,4)) 
    print(block)
    error= [False, False, False,False]
    if ((np.count_nonzero(block[1:,1])) + (np.count_nonzero(block[:,3]))) % 2 != block[0][1]:
        error[0]= True
    if ((np.count_nonzero(block[1:,2])) + (np.count_nonzero(block[:,3]))) % 2 != block[0][2]:
        error[1]= True
    if ((np.count_nonzero(block[1,1:])) + (np.count_nonzero(block[3]))) % 2 != block[1][0]:
        error[2]= True
    if ((np.count_nonzero(block[2,1:])) + (np.count_nonzero(block[3]))) % 2 != block[2][0]:
        error[3]= True
((block_creator(binary_rep[0])))    

[[0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]]
1
